// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

struct MotionPoint
{
	float4 q1;
	float4 q2;
	float4 q3;
	float4 q4;
	float4 q5;
	float cost;
	float offset;
};

RWStructuredBuffer<MotionPoint> MotionTemplates;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	MotionTemplates[0].cost = 15.0;
	MotionTemplates[0].offset = 10.0;
}
